# dclint disable service-image-require-explicit-tag
---
name: Web Scraper
services:
  web-scraper:
    container_name: web_scraper
    image: jnstockley/web-scraper:latest
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data/:/app/data/
    restart: unless-stopped
    healthcheck:
      test: python src/healthcheck.py || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
