---
name: Trivy Security Scan

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  schedule:
    - cron: '22 20 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if Dockerfile exists
        id: dockerfile_check
        run: |
          if [ -f "Dockerfile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        if: steps.dockerfile_check.outputs.exists == 'true' && github.event_name != 'schedule'
        run: |
          docker build -t ${{ github.actor }}/${{ github.event.repository.name }}:latest .

      - name: Check if Docker image exists or build locally
        id: image_check
        if: steps.dockerfile_check.outputs.exists == 'true'
        run: |
          if docker pull ${{ github.actor }}/${{ github.event.repository.name }}:latest >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Building image locally as it doesn't exist remotely"
            docker build -t ${{ github.actor }}/${{ github.event.repository.name }}:latest .
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Trivy vulnerability scanner for Docker image
        if: steps.dockerfile_check.outputs.exists == 'true' && steps.image_check.outputs.exists == 'true'
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ github.actor }}/${{ github.event.repository.name }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner for Python package
        if: steps.dockerfile_check.outputs.exists == 'false' || steps.image_check.outputs.exists == 'false'
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          scanners: 'vuln,secret,misconfig,license'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
